# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: unari.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'unari.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bunari.proto\x12\x05unari\"!\n\x0eRequestPayload\x12\x0f\n\x07message\x18\x01 \x01(\t\"\"\n\x0fResponsePayload\x12\x0f\n\x07message\x18\x01 \x01(\t2J\n\x05Unari\x12\x41\n\x10getServerMessage\x12\x15.unari.RequestPayload\x1a\x16.unari.ResponsePayloadb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'unari_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUESTPAYLOAD']._serialized_start=22
  _globals['_REQUESTPAYLOAD']._serialized_end=55
  _globals['_RESPONSEPAYLOAD']._serialized_start=57
  _globals['_RESPONSEPAYLOAD']._serialized_end=91
  _globals['_UNARI']._serialized_start=93
  _globals['_UNARI']._serialized_end=167
# @@protoc_insertion_point(module_scope)
