# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import unari_pb2 as unari__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in unari_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UnariStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getServerMessage = channel.unary_unary(
                '/unari.Unari/getServerMessage',
                request_serializer=unari__pb2.RequestPayload.SerializeToString,
                response_deserializer=unari__pb2.ResponsePayload.FromString,
                _registered_method=True)


class UnariServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getServerMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UnariServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getServerMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.getServerMessage,
                    request_deserializer=unari__pb2.RequestPayload.FromString,
                    response_serializer=unari__pb2.ResponsePayload.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'unari.Unari', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('unari.Unari', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Unari(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getServerMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/unari.Unari/getServerMessage',
            unari__pb2.RequestPayload.SerializeToString,
            unari__pb2.ResponsePayload.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
